config/routes.rb
Rails.application.routes.draw do
  
  
  get 'medpo/searchmedpo'

  get 'procpo/searchprocpo'

  get 'cie10/searchcie10'

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  authenticated :user do
      root :to => 'main#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  
  get 'programas' => 'main#programas', as: :programas
  get 'riesgo' => 'riesgo#index', as: :riesgo
  get '/riesgo/cancerseno' => 'riesgo#cancerseno', as: :cancerseno

  resources :users_admin, :controller => 'users' 
  match 'users_admin/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  
  
  resources :evolucions do
    get :list, on: :collection
    get :export, on: :collection 
  end

  resources :historia do
    get :list, on: :collection
    get :export, on: :collection 
    
  end

  resources :encuestasenos  do
    get :list, on: :collection
    get :export, on: :collection    
  end  
  resources :divpas do
    get :list, on: :collection
    get :export, on: :collection    
  end
  resources :eps do
    get :list, on: :collection
    get :export, on: :collection
    get :searcheps, :on => :collection
  end
  resources :consultorios do
    get :list, on: :collection
    get :export, on: :collection
  end
  resources :servicios do
    get :list, on: :collection
    get :export, on: :collection
  end
  resources :cita do
    get :list, on: :collection
    get :export, on: :collection    
  end
  resources :especialidads do
    get :list, on: :collection
    get :export, on: :collection
    get :searchespecialidad, :on => :collection
  end
  resources :profesionals do
    get :list, on: :collection
    get :export, on: :collection
    get :searchprofesional, :on => :collection
  end
  resources :pacientes do
    get :list, on: :collection
    get :export, on: :collection    
    get :searchpaciente, :on => :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
	has_many :especialidads
	has_many :profesionals, through: :especialidads		
	has_many :citas, dependent: :destroy

	def especialidads
		Especialidad.where(servicio_id: id,enable:1)
	end
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
 before_filter :authenticate_user!
 load_and_authorize_resource

  # GET /servicios
  # GET /servicios.json
  def index
  end

  def list
  end
  
  # GET /servicios/1
  # GET /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios
  # POST /servicios.json
  def create

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Programa o Grupo de Servicios creado exitosamente.' }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1
  # PATCH/PUT /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to @servicio, notice: 'Programa o Grupo de Servicios actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio.destroy
    respond_to do |format|
      format.html { redirect_to servicios_url, notice: 'Programa o Grupo de Servicios eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_params
      params.require(:servicio).permit(:nombre, :enable)
    end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= form_for(@servicio, html:{class: "ui form cita-form"}) do |f| %>

  <% if @servicio.errors.any? %>
    <div class="ui negative message">
      <div class="header">
        Tiene <%= pluralize(@servicio.errors.count, "error") %>: 
        </div>
        <ul class="list">      
          <% @servicio.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>      
        </ul>
        </div>
  <% end %>

 <div class="five wide required field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, :readonly => f.object.persisted? %>
  </div>
   <div class="five wide field">
    <%= f.label :enable %>
    <%= f.check_box :enable %>
  </div>
  <div class="actions">
   <div class="ui buttons">
      <%= link_to 'Atras', request.referer, :class =>"ui button"%>
       <div class="or" data-text="O"></div>
      <%= f.submit "Guardar Programa o Grupo Servicios", :class =>"ui positive button"  %>
    </div>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
	<div class="column">
<h1>Editando Programa o Grupo de Servicios</h1>

<%= render 'form' %>



</div>
</div>

app/views/servicios/index.html.erb
<div class="ui one column center aligned grid">	
 		<div class="column">
			<h1>Programas y Grupos de Servicios </h1>
		</div>     

<%if can? :create, Servicio %>
<div class="seven wide computer column">
	<div class="ui green segment">
		<%= link_to new_servicio_path do%>
			<h2 class="ui center aligned icon header">		
				<%= image_tag("new.jpeg", :class => "ui centered tiny rounded image")%>
				<div class="content">Crear Programa o Grupo de Servicios </div> 		
			</h2>		
		<%end%>
	</div>
</div>
<% end%>

<%if can? :list, Servicio %>
<div class="seven wide computer column">
	<div class="ui green segment">
	<%= link_to list_servicios_path do%>		
		<h2 class="ui center aligned icon header">
			<%= (image_tag("list.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Listar Programa o Grupo de Servicios
			</div>
		</h2>
	<%end%>		
	</div>
</div>
<% end%>


<%if can? :export, Servicio%>
<div class="seven wide computer column">
	<div class="ui green segment">
		<h2 class="ui center aligned icon header">
			<%= (image_tag("eps.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Reportes
			</div>
		</h2>
	</div>
</div>
<% end%>




</div>
	

app/views/servicios/list.html.erb
<div class="ui two column left aligned grid ">

<%if flash[:notice]%>
<div class="ui warning message">
<div class="header">Notificacion</div>
<p><%= notice %></p>
</div>

<% end %>
<div class="one wide column"></div>
<div class="column">

<h1>Listado de Programas o Grupos de Servicios</h1>

<table class="ui single line celled table">
  <thead>
    <tr>     
      <th>Nombre</th>
      <th>Enable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios.each do |servicio| %>
      <tr>
        <td><%= servicio.nombre %></td>
        <td><%= servicio.enable %></td>
        <td><%= link_to 'Ver', servicio %></td>
        <td><%= link_to 'Editar', edit_servicio_path(servicio) %></td>
        <td><%= link_to 'Eliminar', servicio, method: :delete, data: { confirm: '¿Seguro/a desea eliminar este Programa o Grupo?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Regresar', servicios_path %>
</div>



</div>

app/views/servicios/new.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
	<div class="column">
		<h1>Agregar Programa o Grupo de Servicios</h1>
	
	<div class="seven wide computer column">
	<%= render 'form' %>	
	</div>
	</div>
	
	
</div>

app/views/servicios/show.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
  <div class="column">

<%if flash[:notice]%>
<div class="ui success message">
<div class="header">Formulario Completado</div>
<p><%= notice %></p>
</div>
<% end %>
<p>
  <strong>Nombre:</strong>
  <%= @servicio.nombre %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @servicio.enable %>
</p>

 <%= link_to 'Editar', edit_servicio_path(@servicio), class: "ui button"%>|
 <%= link_to 'Regresar', servicios_path, class: "ui button"%>

    
</div>
</div>