config/routes.rb
Rails.application.routes.draw do
  
  
  get 'medpo/searchmedpo'

  get 'procpo/searchprocpo'

  get 'cie10/searchcie10'

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  authenticated :user do
      root :to => 'main#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  
  get 'programas' => 'main#programas', as: :programas
  get 'riesgo' => 'riesgo#index', as: :riesgo
  get '/riesgo/cancerseno' => 'riesgo#cancerseno', as: :cancerseno

  resources :users_admin, :controller => 'users' 
  match 'users_admin/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  
  
  resources :evolucions do
    get :list, on: :collection
    get :export, on: :collection 
  end

  resources :historia do
    get :list, on: :collection
    get :export, on: :collection 
    
  end

  resources :encuestasenos  do
    get :list, on: :collection
    get :export, on: :collection    
  end  
  resources :divpas do
    get :list, on: :collection
    get :export, on: :collection    
  end
  resources :eps do
    get :list, on: :collection
    get :export, on: :collection
    get :searcheps, :on => :collection
  end
  resources :consultorios do
    get :list, on: :collection
    get :export, on: :collection
  end
  resources :servicios do
    get :list, on: :collection
    get :export, on: :collection
  end
  resources :cita do
    get :list, on: :collection
    get :export, on: :collection    
  end
  resources :especialidads do
    get :list, on: :collection
    get :export, on: :collection
    get :searchespecialidad, :on => :collection
  end
  resources :profesionals do
    get :list, on: :collection
    get :export, on: :collection
    get :searchprofesional, :on => :collection
  end
  resources :pacientes do
    get :list, on: :collection
    get :export, on: :collection    
    get :searchpaciente, :on => :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ep.rb
class Ep < ActiveRecord::Base
	has_many :pacientes


	def self.search(params={})
		busq=3
  		if !(params[:s_eps] == "")
  			where("nombre LIKE ? ", "%#{params[:s_eps]}%")  		
  		else
  			where("enable LIKE ? ","%#{busq}%")  		
  		end
	end
end

app/controllers/eps_controller.rb
class EpsController < ApplicationController
before_filter :authenticate_user!
 load_and_authorize_resource
  # GET /eps
  # GET /eps.json
  def index
   
  end

  def list
     @eps = Ep.where(enable: 1)
    if params[:s_eps]
      @eps = Ep.search(params)
      if Ep.search(params).blank?
        flash[:notice] = "No se obtuvo ningun resultado."         
      end
    else
      @eps = Ep.where(enable: 1)
    end
  end
  
  def searcheps
    @eps = Ep.where('nombre like ? and enable = 1', "%#{params[:query]}%")
  end

  # GET /eps/1
  # GET /eps/1.json
  def show
  end

  # GET /eps/new
  def new
  end

  # GET /eps/1/edit
  def edit
  end

  # POST /eps
  # POST /eps.json
  def create

    respond_to do |format|
      if @ep.save
        format.html { redirect_to @ep, notice: 'EPS creada exitosamente.' }
        format.json { render :show, status: :created, location: @ep }
      else
        format.html { render :new }
        format.json { render json: @ep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eps/1
  # PATCH/PUT /eps/1.json
  def update
    respond_to do |format|
      if @ep.update(ep_params)
        format.html { redirect_to @ep, notice: 'EPS actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @ep }
      else
        format.html { render :edit }
        format.json { render json: @ep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eps/1
  # DELETE /eps/1.json
  def destroy
    @ep.destroy
    respond_to do |format|
      format.html { redirect_to eps_url, notice: 'EPS eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def ep_params
      params.require(:ep).permit(:codigo_eps, :nombre, :enable)
    end
end

app/helpers/eps_helper.rb
module EpsHelper
end

app/views/eps/_form.html.erb
<%= form_for(@ep, html:{class: "ui form cita-form"}) do |f| %>
<% if @ep.errors.any? %>
  <div class="ui negative message">
    <div class="header">
      Tiene <%= pluralize(@ep.errors.count, "error") %>: 
      </div>
      <ul class="list">      
        <% @ep.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>      
      </ul>
      </div>
<% end %>

 <div class="five wide required field">
    <%= f.label :codigo_eps %>
    <%= f.text_field :codigo_eps, :readonly => f.object.persisted? %>
  </div>
    <div class="five wide field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, :readonly => f.object.persisted? %>
  </div>
    <div class="five wide field">
    <%= f.label :enable %>
    <%= f.check_box :enable %>
  </div>
  <div class="actions">
   <div class="ui buttons">
      <%= link_to 'Atras', request.referer, :class =>"ui button"%>
       <div class="or" data-text="O"></div>
      <%= f.submit "Guardar EPS", :class =>"ui positive button"  %>
    </div>
  </div>
<% end %>

app/views/eps/edit.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
	<div class="column">
<h1>Editando EPS</h1>

<%= render 'form' %>



</div>
</div>

app/views/eps/index.html.erb
<div class="ui one column center aligned grid">	
 		<div class="column">
			<h1>EPS </h1>
		</div>     

<%if can? :create, Ep %>
<div class="seven wide computer column">
	<div class="ui green segment">
		<%= link_to new_ep_path do%>
			<h2 class="ui center aligned icon header">		
				<%= image_tag("new.jpeg", :class => "ui centered tiny rounded image")%>
				<div class="content">Crear EPS</div> 		
			</h2>		
		<%end%>
	</div>
</div>
<% end%>

<%if can? :list, Ep %>
<div class="seven wide computer column">
	<div class="ui green segment">
	<%= link_to list_eps_path do%>		
		<h2 class="ui center aligned icon header">
			<%= (image_tag("list.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Listar EPS
			</div>
		</h2>
	<%end%>		
	</div>
</div>
<% end%>

<%if can? :list, Ep%>
<div class="seven wide computer column">
	<div class="ui green segment">			
		<h2 class="ui center aligned icon header">
			<%= (image_tag("search.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Buscar EPS			
			</div>
		</h2>	

		<%= form_tag(list_eps_path, :method => "get", id: "search-form", class: "ui form search-eps") do %>

		<div class="ui one column centered grid">
			<div class="row"></div>
			<div class="eigth wide field">
			<%=label_tag :s_eps,"Nombre EPS"%>
  			<%= text_field_tag :s_eps, params[:s_eps] %> 
  			<%= submit_tag "Buscar" %> 
  			</div>
  		</div>
  		<div class="ui error message"></div>
  			
		<% end %>		
	</div>
</div>
<% end%>

<%if can? :export, Ep%>
<div class="seven wide computer column">
	<div class="ui green segment">
		<h2 class="ui center aligned icon header">
			<%= (image_tag("eps.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Reportes
			</div>
		</h2>
	</div>
</div>
<% end%>




</div>
	

app/views/eps/list.html.erb
<div class="ui two column left aligned grid ">

<%if flash[:notice]%>
<div class="ui warning message">
<div class="header">Notificacion</div>
<p><%= notice %></p>
</div>

<% end %>
<div class="one wide column"></div>
<div class="column">

<h1>Lista de Eps</h1>

<table class="ui single line celled table">
  <thead>
    <tr>
      <th>Codigo eps</th>
      <th>Nombre</th>
      <th>Enable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eps.each do |ep| %>
      <tr>
        <td><%= ep.codigo_eps %></td>
        <td><%= ep.nombre %></td>
        <td><%= ep.enable %></td>
        <td><%= link_to 'Ver', ep %></td>
        <td><%= link_to 'Editar', edit_ep_path(ep) %></td>
        <td><%= link_to 'Eliminar', ep, method: :delete, data: { confirm: '¿Seguro/a desea eliminar esta eps?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'Regresar', eps_path %>

</div>
</div>

app/views/eps/new.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
	<div class="column">
		<h1>Agregar EPS</h1>
	
	<div class="seven wide computer column">
	<%= render 'form' %>	
	</div>
	</div>
	
	
</div>

app/views/eps/show.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
  <div class="column">

<%if flash[:notice]%>
<div class="ui success message">
<div class="header">Formulario Completado</div>
<p><%= notice %></p>
</div>
<% end %>

<p>
  <strong>Codigo eps:</strong>
  <%= @ep.codigo_eps %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @ep.nombre %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @ep.enable %>
</p>

 <%= link_to 'Editar', edit_ep_path(@ep), class: "ui button"%>|
 <%= link_to 'Regresar', eps_path, class: "ui button"%>

    
</div>
</div>