config/routes.rb
Rails.application.routes.draw do
  
  
  get 'medpo/searchmedpo'

  get 'procpo/searchprocpo'

  get 'cie10/searchcie10'

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  authenticated :user do
      root :to => 'main#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  
  get 'programas' => 'main#programas', as: :programas
  get 'riesgo' => 'riesgo#index', as: :riesgo
  get '/riesgo/cancerseno' => 'riesgo#cancerseno', as: :cancerseno

  resources :users_admin, :controller => 'users' 
  match 'users_admin/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  
  
  resources :evolucions do
    get :list, on: :collection
    get :export, on: :collection 
  end

  resources :historia do
    get :list, on: :collection
    get :export, on: :collection 
    
  end

  resources :encuestasenos  do
    get :list, on: :collection
    get :export, on: :collection    
  end  
  resources :divpas do
    get :list, on: :collection
    get :export, on: :collection    
  end
  resources :eps do
    get :list, on: :collection
    get :export, on: :collection
    get :searcheps, :on => :collection
  end
  resources :consultorios do
    get :list, on: :collection
    get :export, on: :collection
  end
  resources :servicios do
    get :list, on: :collection
    get :export, on: :collection
  end
  resources :cita do
    get :list, on: :collection
    get :export, on: :collection    
  end
  resources :especialidads do
    get :list, on: :collection
    get :export, on: :collection
    get :searchespecialidad, :on => :collection
  end
  resources :profesionals do
    get :list, on: :collection
    get :export, on: :collection
    get :searchprofesional, :on => :collection
  end
  resources :pacientes do
    get :list, on: :collection
    get :export, on: :collection    
    get :searchpaciente, :on => :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	has_one :persona, as: :numero, dependent: :destroy
	has_many :direccions, as: :numero, dependent: :destroy			
	belongs_to :ep, :foreign_key => "eps_id"

	before_destroy :destroy_citas, :destroy_encuesta, :destroy_historia, :destroy_evolucion

	accepts_nested_attributes_for :persona, reject_if: proc{ |attr| attr['primer_nombre'].blank? && attr['primer_apellido'].blank? }
	accepts_nested_attributes_for :direccions, reject_if: proc{ |attr| attr['direccion'].blank?}, allow_destroy: true   

	validates :numero_id, :eps_id, :persona, presence: true
	validates :numero_id, uniqueness: true


	def self.search(params={})	
		personaid=" "	
		if !(params[:s_identificacion] == "" && params[:s_pnombre] == "" && params[:s_snombre] == "" && params[:s_papellido] == "" && params[:s_sapellido] == "")
			if (Persona.exists?(["primer_nombre LIKE ? AND segundo_nombre LIKE ? AND primer_apellido LIKE ? AND segundo_apellido LIKE ? AND numero_id LIKE ? AND numero_type ='Paciente'", "%#{params[:s_pnombre]}%", "%#{params[:s_snombre]}%", "%#{params[:s_papellido]}%", "%#{params[:s_sapellido]}%", "%#{params[:s_identificacion]}%"]))
				personaid=Persona.where(["primer_nombre LIKE ? AND segundo_nombre LIKE ? AND primer_apellido LIKE ? AND segundo_apellido LIKE ? AND numero_id LIKE ? AND numero_type ='Paciente'", "%#{params[:s_pnombre]}%", "%#{params[:s_snombre]}%", "%#{params[:s_papellido]}%", "%#{params[:s_sapellido]}%", "%#{params[:s_identificacion]}%"]).select(:numero_id).first.numero_id		
			end
		end
		where("numero_id LIKE ? ", "%#{personaid}%")
	end

	private

	def destroy_citas
     	Citum.where(:paciente_id => self.numero_id ).destroy_all  
   	end

   	def destroy_encuesta
   		Encuestaseno.where(:paciente_id => self.numero_id ).destroy_all 
   	end

   	def destroy_historia
     	Historium.where(:paciente_id => self.numero_id ).destroy_all  
   	end

   	def destroy_evolucion
   		Evolucion.where(:paciente_id => self.numero_id ).destroy_all 
   	end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
    before_filter :authenticate_user!

    load_and_authorize_resource
  
  # GET /pacientes
  # GET /pacientes.json
  def index
    
  end

  def list
     @pacientes = Paciente.all
    if (params[:s_identificacion] && params[:s_pnombre] && params[:s_snombre] && params[:s_papellido] && params[:s_sapellido])
      @pacientes = Paciente.search(params)
      if Paciente.search(params).blank?
        flash[:notice] = "No se obtuvo ningun resultado."         
      end
    else
      @pacientes = Paciente.all
    end      
  end

  def searchpaciente
    @paciente = Paciente.where('numero_id like ?', "%#{params[:query]}%")
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  
  # GET /pacientes/new
  def new  
    @paciente.build_persona
    @paciente.direccions.build
    
  end

  # GET /pacientes/1/edit
  def edit    
    @paciente.direccions.build
  end

  # POST /pacientes
  # POST /pacientes.json
  def create   
    
    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente creado exitosamente.' }
        format.json { render :show, status: :created, location: @paciente }
      else        
        format.html { render :new}
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update    
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente elimiando exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:numero_id, :eps_id, :tipo_usuario,:lugar_nac,:nacionalidad,:escolaridad,:ocupacion,:estrato,:email,:nro_hijos, persona_attributes: [:tipoid, :numero_id, :numero_type, :primer_apellido, :segundo_apellido, :primer_nombre, :segundo_nombre, :estado_civil, :fecha_nac, :sexo, :celular], direccions_attributes:[:id,:numero_id,:numero_type,:barrio,:direccion,:tel,:municipio_id,:_destroy])
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_for(@paciente, html:{class: "ui form paciente-form"}) do |f| %>
 

 <% if @paciente.errors.any? %>
  <div class="ui negative message">
    <div class="header">
      Tiene <%= pluralize(@paciente.errors.count, "error") %>: 
      </div>
      <ul class="list">      
        <% @paciente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>      
      </ul>
      </div>
<% end %>
 <div class="ui error message"></div>

<%= f.fields_for :persona do |persona| %>

    <div class="two fields">
      <div class="five wide field">
        <%= persona.label :tipoid, 'Tipo de Documento' %>
        <div class="two fields">
          <div class="four wide field">
            <%= persona.select :tipoid, options_for_select([['CC', 'CEDULA DE CIUDADANIA'], ['TI','TARJETA DE IDENTIDAD'],['RC','REGISTRO CIVIL'],['CE','CEDULA DE EXTRANJERIA'],['PAS','PASAPORTE'],['MS','MENOR SIN IDENTIFICACION'],['AS','ADULTO SIN IDENTIFICACION'],['NV','CERTIFICADO NACIDO VIVO'] ], selected: persona.object.tipoid, class: "ui fluid normal dropdown")%> 
          </div>
          <div class="eleven wide field">
            <%= if persona.object.persisted?
              text_field_tag "tipo identidad",persona.object.tipoid, :disabled => true 
            else
              text_field_tag "tipo identidad",'CEDULA DE CIUDADANIA', :disabled => true  
            end%> 
          </div>
        </div>
      </div>
      <%end%>
      
      <div class="three wide required field">
        <%= f.label :numero_id %>
        <%= f.number_field :numero_id %>
      </div>
  </div>
     

    <%= f.fields_for :persona do |persona| %>
    <div class="two fields">
      <div class="four wide field">
        <%= persona.label :primer_apellido %>
        <%= persona.text_field :primer_apellido %>
      </div>

      <div class="four wide field">
        <%= persona.label :segundo_apellido %>
        <%= persona.text_field :segundo_apellido %>
      </div>
    </div>
    <div class="two fields">
      <div class="four wide field">
        <%= persona.label :primer_nombre %>
        <%= persona.text_field :primer_nombre %>
      </div>
    
      <div class="four wide field">
        <%= persona.label :segundo_nombre %>
        <%= persona.text_field :segundo_nombre %>
      </div>
    </div>
    <div class="two fields">
      <div class="four wide field">
        <%= label_tag :sexo, "Genero" %>
        <div class="four fields">
          <div class="five wide field">
        <%= persona.select :sexo, options_for_select([['M', 'Masculino'], ['F','Femenino']],selected: persona.object.sexo)%> 
          </div>
          <div class="eleven wide field">
            <%= if persona.object.persisted?
          text_field_tag "Sexo",persona.object.sexo, :disabled => true 
        else
          text_field_tag "Sexo",'Masculino', :disabled => true  
        end%>
        </div>
      </div>
      </div>

      <div class="four wide field">
        <%= persona.label :estado_civil %>
        <%= persona.select :estado_civil, options_for_select([['Soltero/a', 'Soltero/a'], ['Casado/a','Casado/a'],['Divorciado/a','Divorciado/a'],['Viudo/a','Viudo/a'],['Union libre','Union libre']],selected: persona.object.estado_civil)%> 
      </div>
    
    </div>

    <div class="three fields">
      <div class="four wide field">
        <%= persona.label :fecha_nac, "Fecha de Nacimiento" %>
        <div class="inline fields">
        <%= persona.date_select :fecha_nac, :use_short_month=>true, :start_year => 1920 %>
        </div>
      </div>
      <div class="two wide field">
          <%= label_tag :años %>
          <%= number_field_tag :años,value=nil, :disabled => true  %>
        </div>           
        <div class="two wide field">
            <%= label_tag :meses %>
            <%= number_field_tag :meses,value=nil, :disabled => true  %>
        </div>
    
    </div>
    <% end%>
  
    <div class="two fields">
      <div class="five wide field">
      <%= f.label :lugar_nac, "Lugar de Nacimiento" %>
      <%= f.select :lugar_nac, (Divpa.where(enable: 1).collect{|u| [u.nombre_cp, u.cod_cp]}), selected: f.object.lugar_nac%>    
      </div>
      <div class="three wide field">
          <%= f.label :nacionalidad%>
          <%= f.text_field :nacionalidad %>
        </div>
    </div>
    <div class="two fields">
    <div class="two wide field">    
      <%= f.label :nro_hijos, "Numero de hijos" %>
      <%= f.number_field :nro_hijos  %>
      
    </div>
                
   <%= f.fields_for :persona do |persona| %>     
    
    <div class="three wide field">
      <%= persona.label :celular %>
      <%= persona.number_field :celular %>
    </div>   

  <% end%>

  </div>
  <!-- Formulario Direccion -->

<h2>Direccion</h2>
  <%= f.fields_for :direccions do |direccion| %>
    <div class="two fields">
      <div class="four wide field">
       <%= direccion.label :municipio_id, "Lugar de Residencia" %>
       <%= direccion.select :municipio_id, (Divpa.where(enable: 1).collect{|u| [u.nombre_cp, u.cod_cp]}), selected: direccion.object.municipio_id%>
      
      </div>
      <div class="four wide field">
        <%= direccion.label :barrio, "Barrio" %>
        <%= direccion.text_field :barrio %>
      </div>
    </div>
    <div class="two fields">
    <div class="five wide required field">
        <%= direccion.label :direccion, "Direccion" %>
        <%= direccion.text_field :direccion %>
      </div>
    <div class="three wide field">
        <%= direccion.label :tel, "Telefono o Celular" %>
        <%= direccion.number_field :tel %>
      </div>
    </div>   
    <div class="five wide field">
        <%= if direccion.object.persisted?
          direccion.label :_destroy, "Borrar" 
          direccion.check_box :_destroy      
        end %>
      </div>       
    
  <% end %>


<div class="three fields">
  <div class="three wide field">
    <%= f.label :escolaridad %>
    <%= f.select :escolaridad, options_for_select([['Primaria Incompleta', 'Primaria Incompleta'], ['Primaria Completa','Primaria Completa'],['Secundaria Incompleta', 'Secundaria Incompleta'], ['Secundaria Completa','Secundaria Completa'],['Tecnico','Tecnico'],['Tecnologo','Tecnologo'],['Profesional','Profesional'],['Postgrado','Postgrado'],['Analfabeta','Analfabeta']],selected: f.object.escolaridad)%>     
  </div>

  <div class="four wide field">
        <%= f.label :ocupacion%>
        <%= f.text_field :ocupacion %>
  </div>

   <div class="one wide field">
    <%= f.label :estrato %>
    <%= f.select :estrato, options_for_select([['1','1'],['2','2'],['3','3'],['4','4'],['5','5'],['6','6'],['7','7']],selected: f.object.estrato)%>     
  </div>

  </div>
  

  <div class="five wide field">
    <%= label_tag :search_eps, "Buscar EPS" %>
    <div class="ui search search_eps">
    <div class="ui icon input">
        <%= text_field_tag "search_eps","", class:"prompt"  %>
        <i class="search icon"></i>
      </div>
    </div>     
  </div>

<div class="two fields">
  <div class="three wide field ">
  <%= f.label :eps_id, "Codigo EPS" %>
  <%= f.text_field :eps_id, :readonly => true %>
  </div>

  <div class="ten wide field">
    <%= label_tag :nombre_eps, "Nombre EPS" %>   
    <%if f.object.persisted? %>
    <%= text_field_tag :nombre_eps,Ep.where(codigo_eps: f.object.eps_id).first.nombre,:disabled => true%>  
    <%else %>
    <%= text_field_tag :nombre_eps,"",:disabled => true%>  
    <%end %>
  </div>

</div>

  <div class="two fields">
    <div class="three wide field">
    <%= f.label :tipo_usuario %>    
    <%= f.select :tipo_usuario, options_for_select([['Subsidiado', 'Subsidiado'], ['Contributivo','Contributivo']],selected: f.object.tipo_usuario)%> 
  </div>
  <div class="four wide field">
        <%= f.label :email, "Correo" %>
        <%= f.email_field :email %>
   </div>
  </div>
 <div class="actions">
   <div class="ui buttons">
      <%= link_to 'Atras', request.referer, :class =>"ui button"%>
       <div class="or" data-text="O"></div>
      <%= f.submit "Guardar paciente", :class =>"ui positive button"  %>
    </div>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
	<div class="fourteen wide column">
		<h1>Editando Paciente</h1>
	
	<div class="sixteen wide computer column">
	<%= render 'form' %>	
	</div>
	</div>
	
	
</div>

app/views/pacientes/index.html.erb
<div class="ui one column center aligned grid">	
 		<div class="fourteen wide column">
			<h1>Pacientes </h1>
		</div>     

<%if can? :create, Paciente %>
<div class="seven wide computer column">
	<div class="ui green segment">
		<%= link_to new_paciente_path do%>
			<h2 class="ui center aligned icon header">		
				<%= image_tag("new.jpeg", :class => "ui centered tiny rounded image")%>
				<div class="content">Crear Pacientes</div> 		
			</h2>		
		<%end%>
	</div>
</div>
<% end%>

<%if can? :list, Paciente %>
<div class="seven wide computer column">
	<div class="ui green segment">
	<%= link_to list_pacientes_path do%>		
		<h2 class="ui center aligned icon header">
			<%= (image_tag("list.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Listar Pacientes
			</div>
		</h2>
	<%end%>		
	</div>
</div>
<% end%>

<%if can? :list, Paciente%>
<div class="seven wide computer column">
	<div class="ui green segment">			
		<h2 class="ui center aligned icon header">
			<%= (image_tag("search.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Buscar Pacientes
			</div>
		</h2>	
		<%= form_tag(list_pacientes_path, :method => "get", id: "search-form", class:"ui form") do %>
		<div class="fields">				
			<div class="five wide field">
				<%=label_tag :s_identificacion,"Identificacion"%>
				<%=number_field_tag :s_identificacion, params[:s_identificacion] %>
			</div>
			<div class="five wide field">
				<%=label_tag :s_pnombre,"Primer Nombre"%>
				<%=text_field_tag :s_pnombre, params[:s_pnombre] %>
			</div>
			<div class="five wide field">
				<%=label_tag :s_snombre,"Segundo Nombre"%>
				<%=text_field_tag :s_snombre, params[:s_snombre] %>
			</div>
			<div class="five wide field">
				<%=label_tag :s_papellido,"Primer Apellido"%>
				<%=text_field_tag :s_papellido, params[:s_papellido] %>
			</div>	
			<div class="five wide field">
				<%=label_tag :s_sapellido,"Segundo Apellido"%>
				<%=text_field_tag :s_sapellido, params[:s_sapellido] %>
			</div>	
		</div>			
		  	<%= submit_tag "Buscar" %>
		<% end %>		
	</div>
</div>
<% end%>

<%if can? :export, Paciente%>
<div class="seven wide computer column">
	<div class="ui green segment">
		<h2 class="ui center aligned icon header">
			<%= (image_tag("eps.jpg", :class => "ui centered tiny rounded image")) %>
			<div class="content">
				Reportes
			</div>
		</h2>
	</div>
</div>
<% end%>




</div>
	

app/views/pacientes/list.html.erb
<div class="ui two column left aligned grid ">

<%if flash[:notice]%>
<div class="ui warning message">
<div class="header">Notificacion</div>
<p><%= notice %></p>
</div>

<% end %>
<div class="one wide column"></div>
<div class="column">
<h1>Listado de Pacientes</h1>

<table class="ui single line celled table">
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nombres</th>
      <th>Apelllidos</th>
      <th>Tipo de Usuario</th>
      <th>EPS</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.numero_id %></td>
        <td><%= paciente.persona.nombres %></td>
        <td><%= paciente.persona.apellidos %></td>
        <td><%= paciente.tipo_usuario %></td>
        <td><%= paciente.eps_id %></td>
        <td><%= link_to 'Ver', paciente %></td>
        <td><%= link_to 'Editar', edit_paciente_path(paciente) %></td>        
        <td><%= link_to 'Borrar', paciente, method: :delete, data: { confirm: '¿Seguro/a desea eliminar este paciente?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Regresar', pacientes_path %>

</div>
</div>

app/views/pacientes/new.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
	<div class="fourteen wide column">
		<h1>Agregar Paciente</h1>
	
	<div class="sixteen wide computer column">
	<%= render 'form' %>	
	</div>
	</div>
	
	
</div>

app/views/pacientes/show.html.erb
<div class="ui two column left aligned grid ">
<div class="one wide column"></div>
  <div class="column">

<%if flash[:notice]%>
<div class="ui success message">
<div class="header">Formulario Completado</div>
<p><%= notice %></p>
</div>
<% end %>

<p>
  <strong>Tipo de Documento:</strong>
  <%= @paciente.persona.tipoid %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @paciente.persona.numero_id%>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @paciente.persona.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @paciente.persona.apellidos %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @paciente.persona.sexo %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @paciente.persona.estado_civil %>
</p>

<p>
  <strong>Fecha nac:</strong>
  <%= @paciente.persona.fecha_nac %>
</p>

<p>
  <strong>Años:</strong>
  <script type="text/javascript">
      
      document.write(getAge(parseInt(<%= @paciente.persona.fecha_nac.day %>),parseInt(<%= @paciente.persona.fecha_nac.month %>),parseInt(<%= @paciente.persona.fecha_nac.year %>)).years);
      
    </script>
</p>

<p>
  <strong>Meses:</strong>
    <script type="text/javascript">
      document.write(getAge(parseInt(<%= @paciente.persona.fecha_nac.day %>),parseInt(<%= @paciente.persona.fecha_nac.month %>),parseInt(<%= @paciente.persona.fecha_nac.year %>)).months);
    </script>

</p>

<p>
  <strong>Lugar de Nacimiento:</strong>
  <%= @paciente.lugar_nac%>
</p>

<p>
  <strong>Nacionalidad:</strong>
  <%= @paciente.nacionalidad%>
</p>

<p>
  <strong>Numero de hijps:</strong>
  <%= @paciente.nro_hijos %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @paciente.persona.celular %>
</p>



<p>
  <strong>Tipo de Usuario:</strong>
  <%= @paciente.tipo_usuario %>
</p>

<p>
  <strong>EPS:</strong>
  <%= Ep.where(codigo_eps: @paciente.eps_id).select(:nombre).first.nombre %>
</p>

<% if @paciente.direccions.any? %>
   <ul>
    <% @paciente.direccions.each do |direccion| %>
   
      <p>
        <strong>Barrio:</strong>
        <%= direccion.barrio %>
      </p>

      <p>
        <strong>Direccion:</strong>
        <%= direccion.direccion %>
      </p>

      <p>
        <strong>Tel:</strong>
        <%= direccion.tel %>
      </p>

      <p>
        <strong>Departamento:</strong>
        <%= Divpa.where(cod_cp: direccion.municipio_id).select(:nombre_dpto).first.nombre_dpto %>
      </p>

      <p>
        <strong>Municipio:</strong>
        <%= Divpa.where(cod_cp: direccion.municipio_id).select(:nombre_cp).first.nombre_cp %>
      </p>
          
    <% end %>
        </ul>  
<% else %>
 <div class="ui info message">    
    <div class="header">
      Informacion Adicional
    </div>
    <p>no hay direcciones</p>  
  </div>  
<% end %>

 <%= link_to 'Editar', edit_paciente_path(@paciente), class: "ui button"%>|
 <%= link_to 'Regresar', pacientes_path, class: "ui button"%>

    
</div>
</div>